<?php

    /**
     * For full documentation, please visit: http://docs.reduxframework.com/
     * For a more extensive sample-config file, you may look at:
     * https://github.com/reduxframework/redux-framework/blob/master/sample/sample-config.php
     */

    if ( ! class_exists( 'Redux' ) ) {
        return;
    }

    // This is your option name where all the Redux data is stored.
    $opt_name = "hola_options";

    /**
     * ---> SET ARGUMENTS
     * All the possible arguments for Redux.
     * For full documentation on arguments, please refer to: https://github.com/ReduxFramework/ReduxFramework/wiki/Arguments
     * */

    $theme = wp_get_theme(); // For use with some settings. Not necessary.

    $args = array(
        'opt_name' => 'hola_options',
        'use_cdn' => TRUE,
        'display_name' => 'Hola',
        'page_slug' => 'hola_options',
        'page_title' => 'Hola',
        'intro_text' => 'Welcome to Hola - Minimal, Multipurpose Wordpress Theme',
        'footer_text' => 'A Theme by WPGeeky',
        'admin_bar' => TRUE,
        'menu_type' => 'menu',
        'menu_title' => 'Hola',
        'menu_icon' => 'dashicons-layout',
        'allow_sub_menu' => TRUE,
        'page_parent_post_type' => 'your_post_type',
        'page_priority' => '4',
        'customizer' => TRUE,
        'default_show' => TRUE,
        'default_mark' => '*',
        'hints' => array(
            'icon' => 'el el-address-book-alt',
            'icon_position' => 'right',
            'icon_size' => 'normal',
            'tip_style' => array(
                'color' => 'light',
            ),
            'tip_position' => array(
                'my' => 'top left',
                'at' => 'bottom right',
            ),
            'tip_effect' => array(
                'show' => array(
                    'duration' => '500',
                    'event' => 'mouseover',
                ),
                'hide' => array(
                    'duration' => '500',
                    'event' => 'mouseleave unfocus',
                ),
            ),
        ),
        'output' => TRUE,
        'output_tag' => TRUE,
        'settings_api' => TRUE,
        'compiler' => TRUE,
        'page_permissions' => 'manage_options',
        'save_defaults' => TRUE,
        'show_import_export' => TRUE,
        'database' => 'options',
        'transient_time' => '3600',
        'network_sites' => TRUE,
    );

    Redux::setArgs( $opt_name, $args );

    /*
     * ---> END ARGUMENTS
     */

    /*
     * ---> START HELP TABS
     */

    $tabs = array(
        array(
            'id'      => 'redux-help-tab-1',
            'title'   => __( 'Theme Information 1', 'hola' ),
            'content' => __( '<p>This is the tab content, HTML is allowed.</p>', 'hola' )
        ),
        array(
            'id'      => 'redux-help-tab-2',
            'title'   => __( 'Theme Information 2', 'hola' ),
            'content' => __( '<p>This is the tab content, HTML is allowed.</p>', 'hola' )
        )
    );
    Redux::setHelpTab( $opt_name, $tabs );

    // Set the help sidebar
    $content = __( '<p>This is the sidebar content, HTML is allowed.</p>', 'hola' );
    Redux::setHelpSidebar( $opt_name, $content );


    /*
     * <--- END HELP TABS
     */


    /*
     *
     * ---> START SECTIONS
     *
     */

    Redux::setSection( $opt_name, array(
        'title'  => __( 'Default Settings', 'hola' ),
        'id'     => 'default-settings',
        'desc'   => __( 'Theme\'s default settings.', 'hola' ),
        'icon'   => 'el el-home',
        'fields' => array(
            array(
                'id'       => 'opt-text',
                'type'     => 'text',
                'title'    => __( 'Example Text', 'hola' ),
                'desc'     => __( 'Example description.', 'hola' ),
                'subtitle' => __( 'Example subtitle.', 'hola' ),
            )
        )
    ) );

    Redux::setSection( $opt_name, array(
        'title' => __( 'Homepage', 'hola' ),
        'id'    => 'homepage',
        'desc'  => __( 'Homepage settings.', 'hola' ),
        'icon'  => 'el el-home'
    ) );

    Redux::setSection( $opt_name, array(
        'title'      => __( 'Slider Section', 'hola' ),
        'desc'       => __( 'Slider Section settings for home page', 'hola' ),
        'id'         => 'home-slider',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'home-slider-h1',
                'type'     => 'text',
                'title'    => __( 'First Heading', 'hola' ),
                'desc'     => __( 'Please input first heading here.', 'hola' ),
                'default'  => 'I AM',
            ),
	        array(
                'id'       => 'home-slider-h2',
                'type'     => 'text',
                'title'    => __( 'Second Heading', 'hola' ),
                'subtitle'    => __( 'You or your company name.', 'hola' ),
                'desc'     => __( 'Please input second heading here.', 'hola' ),
                'default'  => 'DATIM WILLIAMS',
            ),
	        array(
                'id'       => 'home-slider-p1',
                'type'     => 'text',
                'title'    => __( 'First visible text', 'hola' ),
                'desc'     => __( 'Please input first visible text here.', 'hola' ),
                'default'  => 'A PROFESSIONAL DEVELOPER',
            ),
	        array(
                'id'       => 'home-slider-p',
                'type'     => 'multi_text',
                'title'    => __( 'Scroll text', 'hola' ),
                'desc'     => __( 'Please input scroll text here.', 'hola' ),
                'default' => array(
	                'mostly, i work with php,',
	                'wordpress and laravel',
	                'along with react and angularjs',
                ),
            ),
	        array(
		        'id'       => 'home-slider-bg',
		        'type'     => 'media',
		        'url'      => true,
		        'title'    => __('Slider Background Image', 'hola'),
		        'preview'  => true,
		        'subtitle' => __('Upload any images for background', 'hola'),
		        'default'  => array(
			        'url'  => get_template_directory_uri() . '/img/bg/slider-bg.jpg'
		        ),
	        ),
	        
        )
    ) );

    Redux::setSection( $opt_name, array(
        'title'      => __( 'About Section', 'hola' ),
        'desc'       => __( 'Settings for about section', 'hola' ),
        'id'         => 'home-about',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'home-about-heading',
                'type'     => 'text',
                'title'    => __( 'About Section Heading', 'hola' ),
                'subtitle' => __( 'Title of the about section', 'hola' ),
                'desc'     => __( 'Please input the section title.', 'hola' ),
                'default'  => 'About Me',
            ),
	        array(
		        'id'       => 'home-about-description',
		        'type'     => 'textarea',
		        'title'    => __( 'About you or your company.', 'hola' ),
		        'subtitle' => __( 'Descriptive text about yourself.', 'hola' ),
		        'desc'     => __( 'Please input description text.', 'hola' ),
		        'default'  => 'Almost before we knew it we had left the ground.The face of the moon was in shadow. The spectacle before was indeed sublime. All their equipment and instruments are alive. Their equipment and instruments are alive. I watched the storm so beautiful yet terrific.Silver mist suffused the deck of the ship. It was going to be a lonely trip back. Silver mist suffused is the deck of the ship. The face of the moon was in shadow. Waves flung themselves at the blue evening. Red silhouetted the jagged edge of a wing.',
	        ),
	        array(
                'id'       => 'home-about-feature-1',
                'type'     => 'text',
                'title'    => __( 'Feature One Heading', 'hola' ),
                'subtitle' => __( 'Feature name', 'hola' ),
                'desc'     => __( 'Please input the feature name.', 'hola' ),
                'default'  => 'FLEXIBLE REDY',
            ),
	        array(
		        'id'       => 'home-about-feature-1-description',
		        'type'     => 'textarea',
		        'title'    => __( 'About feature one.', 'hola' ),
		        'subtitle' => __( 'Descriptive text about feature one.', 'hola' ),
		        'desc'     => __( 'Please input feature one description text.', 'hola' ),
		        'default'  => 'The face of the moon was in shadow.Waves flung themselves at the blue evening. Red flair silhouetted the jagged edge of a wing.',
	        ),
	        array(
                'id'       => 'home-about-feature-2',
                'type'     => 'text',
                'title'    => __( 'Feature Two Heading', 'hola' ),
                'subtitle' => __( 'Feature name', 'hola' ),
                'desc'     => __( 'Please input the feature name.', 'hola' ),
                'default'  => 'UNLOCK FEATURES',
            ),
	        array(
		        'id'       => 'home-about-feature-2-description',
		        'type'     => 'textarea',
		        'title'    => __( 'About feature two.', 'hola' ),
		        'subtitle' => __( 'Descriptive text about feature two.', 'hola' ),
		        'desc'     => __( 'Please input feature two description text.', 'hola' ),
		        'default'  => 'The face of the moon was in shadow.Waves flung themselves at the blue evening. Red flair silhouetted the jagged edge of a wing.',
	        ),
	        
	        
        )
    ) );

    Redux::setSection( $opt_name, array(
        'title'      => __( 'Skills Section', 'hola' ),
        'desc'       => __( 'Settings for skills section', 'hola' ),
        'id'         => 'home-skills',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'home-skills-heading',
                'type'     => 'text',
                'title'    => __( 'Skill Section Heading', 'hola' ),
                'desc'     => __( 'Please input the skill section title.', 'hola' ),
                'default'  => 'My Skills',
            ),
	        array(
                'id'       => 'home-skills-name-one',
                'type'     => 'text',
                'title'    => __( 'Skill One Name', 'hola' ),
                'subtitle' => __( 'Name of the skill', 'hola' ),
                'desc'     => __( 'Please input the skill name.', 'hola' ),
                'default'  => 'WordPress',
            ),
	        array(
                'id'       => 'home-skills-percent-one',
                'type'     => 'text',
                'title'    => __( 'Skill One Value', 'hola' ),
                'subtitle' => __( 'Value of the skill in percent', 'hola' ),
                'desc'     => __( 'Please input the skill value in 100.', 'hola' ),
                'default'  => '93',
            ),
	         array(
                'id'       => 'home-skills-name-two',
                'type'     => 'text',
                'title'    => __( 'Skill Two Name', 'hola' ),
                'subtitle' => __( 'Name of the skill', 'hola' ),
                'desc'     => __( 'Please input the skill name.', 'hola' ),
                'default'  => 'JavaScript',
            ),
	        array(
                'id'       => 'home-skills-percent-two',
                'type'     => 'text',
                'title'    => __( 'Skill Two Value', 'hola' ),
                'subtitle' => __( 'Value of the skill in percent', 'hola' ),
                'desc'     => __( 'Please input the skill value in 100.', 'hola' ),
                'default'  => '85',
            ),
	         array(
                'id'       => 'home-skills-name-three',
                'type'     => 'text',
                'title'    => __( 'Skill Three Name', 'hola' ),
                'subtitle' => __( 'Name of the skill', 'hola' ),
                'desc'     => __( 'Please input the skill name.', 'hola' ),
                'default'  => 'CSS',
            ),
	        array(
                'id'       => 'home-skills-percent-three',
                'type'     => 'text',
                'title'    => __( 'Skill Three Value', 'hola' ),
                'subtitle' => __( 'Value of the skill in percent', 'hola' ),
                'desc'     => __( 'Please input the skill value in 100.', 'hola' ),
                'default'  => '97',
            ),
	        
	         array(
                'id'       => 'home-skills-name-four',
                'type'     => 'text',
                'title'    => __( 'Skill Four Name', 'hola' ),
                'subtitle' => __( 'Name of the skill', 'hola' ),
                'desc'     => __( 'Please input the skill name.', 'hola' ),
                'default'  => 'PHP',
            ),
	        array(
                'id'       => 'home-skills-percent-four',
                'type'     => 'text',
                'title'    => __( 'Skill Four Value', 'hola' ),
                'subtitle' => __( 'Value of the skill in percent', 'hola' ),
                'desc'     => __( 'Please input the skill value in 100.', 'hola' ),
                'default'  => '90',
            ),
	        
        )
    ) );

    Redux::setSection( $opt_name, array(
        'title'      => __( 'Service Section', 'hola' ),
        'desc'       => __( 'Settings for service section', 'hola' ),
        'id'         => 'home-service',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'home-service-heading',
                'type'     => 'text',
                'title'    => __( 'Service Section Heading', 'hola' ),
                'desc'     => __( 'Please input the service section title.', 'hola' ),
                'default'  => 'MY SEVICES',
            ),
	        array(
                'id'       => 'home-service-description',
                'type'     => 'textarea',
                'title'    => __( 'Service Section Description', 'hola' ),
                'desc'     => __( 'Please input the service section description.', 'hola' ),
                'default'  => 'All their equipment and instruments are alive. I watched the storm so beautiful yet terrific.Silver mist suffused the deck of the ship. The recorded voice scratched speaker.',
            ),
	        array(
                'id'       => 'home-service-one-title',
                'type'     => 'text',
                'title'    => __( 'Service One Title', 'hola' ),
                'desc'     => __( 'Please input the service title.', 'hola' ),
                'default'  => 'UI/UX DESIGN',
            ),
	        array(
		        'id'       => 'home-service-one-icon',
		        'type'     => 'select',
		        'title'    => __('Select Service Icon', 'hola'),
		        'desc'     => __('Please selec service icon from the list.', 'hola').' <a href="http://rhythm.nikadevs.com/content/icons-et-line">Full list</a>.',
		        // Must provide key => value pairs for select options
		        'options'  => array(
			        'icon-mobile' => '<span class="icon-mobile"></span> icon-mobile',
			        'icon-laptop' => '<span class="icon-laptop"></span> icon-laptop',
			        'icon-desktop' => '<span class="icon-desktop"></span> icon-desktop',
			        'icon-tablet' => '<span class="icon-tablet"></span> icon-tablet',
			        'icon-phone' => '<span class="icon-phone"></span> icon-phone',
			        'icon-document' => '<span class="icon-document"></span> icon-document',
			        'icon-documents' => '<span class="icon-documents"></span> icon-documents',
			        'icon-search' => '<span class="icon-search"></span> icon-search',
			        'icon-clipboard' => '<span class="icon-clipboard"></span> icon-clipboard',
			        'icon-newspaper' => '<span class="icon-newspaper"></span> icon-newspaper',
			        'icon-notebook' => '<span class="icon-notebook"></span> icon-notebook',
			        'icon-book-open' => '<span class="icon-book-open"></span> icon-book-open',
			        'icon-browser' => '<span class="icon-browser"></span> icon-browser',
			        'icon-calendar' => '<span class="icon-calendar"></span> icon-calendar',
			        'icon-presentation' => '<span class="icon-presentation"></span> icon-presentation',
			        'icon-picture' => '<span class="icon-picture"></span> icon-picture',
			        'icon-pictures' => '<span class="icon-pictures"></span> icon-pictures',
			        'icon-video' => '<span class="icon-video"></span> icon-video',
			        'icon-camera' => '<span class="icon-camera"></span> icon-camera',
			        'icon-printer' => '<span class="icon-printer"></span> icon-printer',
			        'icon-toolbox' => '<span class="icon-toolbox"></span> icon-toolbox',
			        'icon-briefcase' => '<span class="icon-briefcase"></span> icon-briefcase',
			        'icon-wallet' => '<span class="icon-wallet"></span> icon-wallet',
			        'icon-gift' => '<span class="icon-gift"></span> icon-gift',
			        'icon-bargraph' => '<span class="icon-bargraph"></span> icon-bargraph',
			        'icon-grid' => '<span class="icon-grid"></span> icon-grid',
			        'icon-expand' => '<span class="icon-expand"></span> icon-expand',
			        'icon-focus' => '<span class="icon-focus"></span> icon-focus',
			        'icon-edit' => '<span class="icon-edit"></span> icon-edit',
			        'icon-adjustments' => '<span class="icon-adjustments"></span> icon-adjustments',
			        'icon-ribbon' => '<span class="icon-ribbon"></span> icon-ribbon',
			        'icon-hourglass' => '<span class="icon-hourglass"></span> icon-hourglass',
			        'icon-lock' => '<span class="icon-lock"></span> icon-lock',
			        'icon-megaphone' => '<span class="icon-megaphone"></span> icon-megaphone',
			        'icon-shield' => '<span class="icon-shield"></span> icon-shield',
			        'icon-trophy' => '<span class="icon-trophy"></span> icon-trophy',
			        'icon-flag' => '<span class="icon-flag"></span> icon-flag',
			        'icon-map' => '<span class="icon-map"></span> icon-map',
			        'icon-puzzle' => '<span class="icon-puzzle"></span> icon-puzzle',
			        'icon-basket' => '<span class="icon-basket"></span> icon-basket',
			        'icon-envelope' => '<span class="icon-envelope"></span> icon-envelope',
			        'icon-streetsign' => '<span class="icon-streetsign"></span> icon-streetsign',
			        'icon-telescope' => '<span class="icon-telescope"></span> icon-telescope',
			        'icon-gears' => '<span class="icon-gears"></span> icon-gears',
			        'icon-key' => '<span class="icon-key"></span> icon-key',
			        'icon-paperclip' => '<span class="icon-paperclip"></span> icon-paperclip',
			        'icon-attachment' => '<span class="icon-attachment"></span> icon-attachment',
			        'icon-pricetags' => '<span class="icon-pricetags"></span> icon-pricetags',
			        'icon-lightbulb' => '<span class="icon-lightbulb"></span> icon-lightbulb',
			        'icon-layers' => '<span class="icon-layers"></span> icon-layers',
			        'icon-pencil' => '<span class="icon-pencil"></span> icon-pencil',
			        'icon-tools' => '<span class="icon-tools"></span> icon-tools',
			        'icon-tools-2' => '<span class="icon-tools-2"></span> icon-tools-2',
			        'icon-scissors' => '<span class="icon-scissors"></span> icon-scissors',
			        'icon-paintbrush' => '<span class="icon-paintbrush"></span> icon-paintbrush',
			        'icon-magnifying-glass' => '<span class="icon-magnifying-glass"></span> icon-magnifying-glass',
			        'icon-circle-compass' => '<span class="icon-circle-compass"></span> icon-circle-compass',
			        'icon-linegraph' => '<span class="icon-linegraph"></span> icon-linegraph',
			        'icon-mic' => '<span class="icon-mic"></span> icon-mic',
			        'icon-strategy' => '<span class="icon-strategy"></span> icon-strategy',
			        'icon-beaker' => '<span class="icon-beaker"></span> icon-beaker',
			        'icon-caution' => '<span class="icon-caution"></span> icon-caution',
			        'icon-recycle' => '<span class="icon-recycle"></span> icon-recycle',
			        'icon-anchor' => '<span class="icon-anchor"></span> icon-anchor',
			        'icon-profile-male' => '<span class="icon-profile-male"></span> icon-profile-male',
			        'icon-profile-female' => '<span class="icon-profile-female"></span> icon-profile-female',
			        'icon-bike' => '<span class="icon-bike"></span> icon-bike',
			        'icon-hotairballoon' => '<span class="icon-hotairballoon"></span> icon-hotairballoon',
			        'icon-globe' => '<span class="icon-globe"></span> icon-globe',
			        'icon-genius' => '<span class="icon-genius"></span> icon-genius',
			        'icon-map-pin' => '<span class="icon-map-pin"></span> icon-map-pin',
			        'icon-dial' => '<span class="icon-dial"></span> icon-dial',
			        'icon-chat' => '<span class="icon-chat"></span> icon-chat',
			        'icon-heart' => '<span class="icon-heart"></span> icon-heart',
			        'icon-cloud' => '<span class="icon-cloud"></span> icon-cloud',
			        'icon-upload' => '<span class="icon-upload"></span> icon-upload',
			        'icon-download' => '<span class="icon-download"></span> icon-download',
			        'icon-target' => '<span class="icon-target"></span> icon-target',
			        'icon-hazardous' => '<span class="icon-hazardous"></span> icon-hazardous',
			        'icon-piechart' => '<span class="icon-piechart"></span> icon-piechart',
			        'icon-speedometer' => '<span class="icon-speedometer"></span> icon-speedometer',
			        'icon-global' => '<span class="icon-global"></span> icon-global',
			        'icon-compass' => '<span class="icon-compass"></span> icon-compass',
			        'icon-lifesaver' => '<span class="icon-lifesaver"></span> icon-lifesaver',
			        'icon-clock' => '<span class="icon-clock"></span> icon-clock',
			        'icon-aperture' => '<span class="icon-aperture"></span> icon-aperture',
			        'icon-quote' => '<span class="icon-quote"></span> icon-quote',
			        'icon-scope' => '<span class="icon-scope"></span> icon-scope',
			        'icon-alarmclock' => '<span class="icon-alarmclock"></span> icon-alarmclock',
			        'icon-refresh' => '<span class="icon-refresh"></span> icon-refresh',
			        'icon-happy' => '<span class="icon-happy"></span> icon-happy',
			        'icon-sad' => '<span class="icon-sad"></span> icon-sad',
			        'icon-facebook' => '<span class="icon-facebook"></span> icon-facebook',
			        'icon-twitter' => '<span class="icon-twitter"></span> icon-twitter',
			        'icon-googleplus' => '<span class="icon-googleplus"></span> icon-googleplus',
			        'icon-rss' => '<span class="icon-rss"></span> icon-rss',
			        'icon-tumblr' => '<span class="icon-tumblr"></span> icon-tumblr',
			        'icon-linkedin' => '<span class="icon-linkedin"></span> icon-linkedin',
			        'icon-dribbble' => '<span class="icon-dribbble"></span> icon-dribbble',
		        ),
		        'default'  => 'icon-layers',
	        ),
	        array(
		        'id'       => 'home-service-one-description',
		        'type'     => 'textarea',
		        'title'    => __( 'Service One Description', 'hola' ),
		        'desc'     => __( 'Please input the service description.', 'hola' ),
		        'default'  => 'Then came the night of the first falling star. She stared through the window at the stars. I watched the storm so beautiful yet terrific.',
	        ),
	        
	        array(
                'id'       => 'home-service-two-title',
                'type'     => 'text',
                'title'    => __( 'Service Two Title', 'hola' ),
                'desc'     => __( 'Please input the service title.', 'hola' ),
                'default'  => 'DEVELOPMENT',
            ),
	        array(
		        'id'       => 'home-service-two-icon',
		        'type'     => 'select',
		        'title'    => __('Select Service Icon', 'hola'),
		        'desc'     => __('Please selec service icon from the list.', 'hola').' <a href="http://rhythm.nikadevs.com/content/icons-et-line">Full list</a>.',
		        // Must provide key => value pairs for select options
		        'options'  => array(
			        'icon-mobile' => '<span class="icon-mobile"></span> icon-mobile',
			        'icon-laptop' => '<span class="icon-laptop"></span> icon-laptop',
			        'icon-desktop' => '<span class="icon-desktop"></span> icon-desktop',
			        'icon-tablet' => '<span class="icon-tablet"></span> icon-tablet',
			        'icon-phone' => '<span class="icon-phone"></span> icon-phone',
			        'icon-document' => '<span class="icon-document"></span> icon-document',
			        'icon-documents' => '<span class="icon-documents"></span> icon-documents',
			        'icon-search' => '<span class="icon-search"></span> icon-search',
			        'icon-clipboard' => '<span class="icon-clipboard"></span> icon-clipboard',
			        'icon-newspaper' => '<span class="icon-newspaper"></span> icon-newspaper',
			        'icon-notebook' => '<span class="icon-notebook"></span> icon-notebook',
			        'icon-book-open' => '<span class="icon-book-open"></span> icon-book-open',
			        'icon-browser' => '<span class="icon-browser"></span> icon-browser',
			        'icon-calendar' => '<span class="icon-calendar"></span> icon-calendar',
			        'icon-presentation' => '<span class="icon-presentation"></span> icon-presentation',
			        'icon-picture' => '<span class="icon-picture"></span> icon-picture',
			        'icon-pictures' => '<span class="icon-pictures"></span> icon-pictures',
			        'icon-video' => '<span class="icon-video"></span> icon-video',
			        'icon-camera' => '<span class="icon-camera"></span> icon-camera',
			        'icon-printer' => '<span class="icon-printer"></span> icon-printer',
			        'icon-toolbox' => '<span class="icon-toolbox"></span> icon-toolbox',
			        'icon-briefcase' => '<span class="icon-briefcase"></span> icon-briefcase',
			        'icon-wallet' => '<span class="icon-wallet"></span> icon-wallet',
			        'icon-gift' => '<span class="icon-gift"></span> icon-gift',
			        'icon-bargraph' => '<span class="icon-bargraph"></span> icon-bargraph',
			        'icon-grid' => '<span class="icon-grid"></span> icon-grid',
			        'icon-expand' => '<span class="icon-expand"></span> icon-expand',
			        'icon-focus' => '<span class="icon-focus"></span> icon-focus',
			        'icon-edit' => '<span class="icon-edit"></span> icon-edit',
			        'icon-adjustments' => '<span class="icon-adjustments"></span> icon-adjustments',
			        'icon-ribbon' => '<span class="icon-ribbon"></span> icon-ribbon',
			        'icon-hourglass' => '<span class="icon-hourglass"></span> icon-hourglass',
			        'icon-lock' => '<span class="icon-lock"></span> icon-lock',
			        'icon-megaphone' => '<span class="icon-megaphone"></span> icon-megaphone',
			        'icon-shield' => '<span class="icon-shield"></span> icon-shield',
			        'icon-trophy' => '<span class="icon-trophy"></span> icon-trophy',
			        'icon-flag' => '<span class="icon-flag"></span> icon-flag',
			        'icon-map' => '<span class="icon-map"></span> icon-map',
			        'icon-puzzle' => '<span class="icon-puzzle"></span> icon-puzzle',
			        'icon-basket' => '<span class="icon-basket"></span> icon-basket',
			        'icon-envelope' => '<span class="icon-envelope"></span> icon-envelope',
			        'icon-streetsign' => '<span class="icon-streetsign"></span> icon-streetsign',
			        'icon-telescope' => '<span class="icon-telescope"></span> icon-telescope',
			        'icon-gears' => '<span class="icon-gears"></span> icon-gears',
			        'icon-key' => '<span class="icon-key"></span> icon-key',
			        'icon-paperclip' => '<span class="icon-paperclip"></span> icon-paperclip',
			        'icon-attachment' => '<span class="icon-attachment"></span> icon-attachment',
			        'icon-pricetags' => '<span class="icon-pricetags"></span> icon-pricetags',
			        'icon-lightbulb' => '<span class="icon-lightbulb"></span> icon-lightbulb',
			        'icon-layers' => '<span class="icon-layers"></span> icon-layers',
			        'icon-pencil' => '<span class="icon-pencil"></span> icon-pencil',
			        'icon-tools' => '<span class="icon-tools"></span> icon-tools',
			        'icon-tools-2' => '<span class="icon-tools-2"></span> icon-tools-2',
			        'icon-scissors' => '<span class="icon-scissors"></span> icon-scissors',
			        'icon-paintbrush' => '<span class="icon-paintbrush"></span> icon-paintbrush',
			        'icon-magnifying-glass' => '<span class="icon-magnifying-glass"></span> icon-magnifying-glass',
			        'icon-circle-compass' => '<span class="icon-circle-compass"></span> icon-circle-compass',
			        'icon-linegraph' => '<span class="icon-linegraph"></span> icon-linegraph',
			        'icon-mic' => '<span class="icon-mic"></span> icon-mic',
			        'icon-strategy' => '<span class="icon-strategy"></span> icon-strategy',
			        'icon-beaker' => '<span class="icon-beaker"></span> icon-beaker',
			        'icon-caution' => '<span class="icon-caution"></span> icon-caution',
			        'icon-recycle' => '<span class="icon-recycle"></span> icon-recycle',
			        'icon-anchor' => '<span class="icon-anchor"></span> icon-anchor',
			        'icon-profile-male' => '<span class="icon-profile-male"></span> icon-profile-male',
			        'icon-profile-female' => '<span class="icon-profile-female"></span> icon-profile-female',
			        'icon-bike' => '<span class="icon-bike"></span> icon-bike',
			        'icon-hotairballoon' => '<span class="icon-hotairballoon"></span> icon-hotairballoon',
			        'icon-globe' => '<span class="icon-globe"></span> icon-globe',
			        'icon-genius' => '<span class="icon-genius"></span> icon-genius',
			        'icon-map-pin' => '<span class="icon-map-pin"></span> icon-map-pin',
			        'icon-dial' => '<span class="icon-dial"></span> icon-dial',
			        'icon-chat' => '<span class="icon-chat"></span> icon-chat',
			        'icon-heart' => '<span class="icon-heart"></span> icon-heart',
			        'icon-cloud' => '<span class="icon-cloud"></span> icon-cloud',
			        'icon-upload' => '<span class="icon-upload"></span> icon-upload',
			        'icon-download' => '<span class="icon-download"></span> icon-download',
			        'icon-target' => '<span class="icon-target"></span> icon-target',
			        'icon-hazardous' => '<span class="icon-hazardous"></span> icon-hazardous',
			        'icon-piechart' => '<span class="icon-piechart"></span> icon-piechart',
			        'icon-speedometer' => '<span class="icon-speedometer"></span> icon-speedometer',
			        'icon-global' => '<span class="icon-global"></span> icon-global',
			        'icon-compass' => '<span class="icon-compass"></span> icon-compass',
			        'icon-lifesaver' => '<span class="icon-lifesaver"></span> icon-lifesaver',
			        'icon-clock' => '<span class="icon-clock"></span> icon-clock',
			        'icon-aperture' => '<span class="icon-aperture"></span> icon-aperture',
			        'icon-quote' => '<span class="icon-quote"></span> icon-quote',
			        'icon-scope' => '<span class="icon-scope"></span> icon-scope',
			        'icon-alarmclock' => '<span class="icon-alarmclock"></span> icon-alarmclock',
			        'icon-refresh' => '<span class="icon-refresh"></span> icon-refresh',
			        'icon-happy' => '<span class="icon-happy"></span> icon-happy',
			        'icon-sad' => '<span class="icon-sad"></span> icon-sad',
			        'icon-facebook' => '<span class="icon-facebook"></span> icon-facebook',
			        'icon-twitter' => '<span class="icon-twitter"></span> icon-twitter',
			        'icon-googleplus' => '<span class="icon-googleplus"></span> icon-googleplus',
			        'icon-rss' => '<span class="icon-rss"></span> icon-rss',
			        'icon-tumblr' => '<span class="icon-tumblr"></span> icon-tumblr',
			        'icon-linkedin' => '<span class="icon-linkedin"></span> icon-linkedin',
			        'icon-dribbble' => '<span class="icon-dribbble"></span> icon-dribbble',
		        ),
		        'default'  => 'icon-tools',
	        ),
	        array(
		        'id'       => 'home-service-two-description',
		        'type'     => 'textarea',
		        'title'    => __( 'Service Two Description', 'hola' ),
		        'desc'     => __( 'Please input the service description.', 'hola' ),
		        'default'  => 'Then came the night of the first falling star. She stared through the window at the stars. I watched the storm so beautiful yet terrific.',
	        ),
	        
	        array(
                'id'       => 'home-service-three-title',
                'type'     => 'text',
                'title'    => __( 'Service Three Title', 'hola' ),
                'desc'     => __( 'Please input the service title.', 'hola' ),
                'default'  => 'WEB DESIGN',
            ),
	        array(
		        'id'       => 'home-service-three-icon',
		        'type'     => 'select',
		        'title'    => __('Select Service Icon', 'hola'),
		        'desc'     => __('Please selec service icon from the list.', 'hola').' <a href="http://rhythm.nikadevs.com/content/icons-et-line">Full list</a>.',
		        // Must provide key => value pairs for select options
		        'options'  => array(
			        'icon-mobile' => '<span class="icon-mobile"></span> icon-mobile',
			        'icon-laptop' => '<span class="icon-laptop"></span> icon-laptop',
			        'icon-desktop' => '<span class="icon-desktop"></span> icon-desktop',
			        'icon-tablet' => '<span class="icon-tablet"></span> icon-tablet',
			        'icon-phone' => '<span class="icon-phone"></span> icon-phone',
			        'icon-document' => '<span class="icon-document"></span> icon-document',
			        'icon-documents' => '<span class="icon-documents"></span> icon-documents',
			        'icon-search' => '<span class="icon-search"></span> icon-search',
			        'icon-clipboard' => '<span class="icon-clipboard"></span> icon-clipboard',
			        'icon-newspaper' => '<span class="icon-newspaper"></span> icon-newspaper',
			        'icon-notebook' => '<span class="icon-notebook"></span> icon-notebook',
			        'icon-book-open' => '<span class="icon-book-open"></span> icon-book-open',
			        'icon-browser' => '<span class="icon-browser"></span> icon-browser',
			        'icon-calendar' => '<span class="icon-calendar"></span> icon-calendar',
			        'icon-presentation' => '<span class="icon-presentation"></span> icon-presentation',
			        'icon-picture' => '<span class="icon-picture"></span> icon-picture',
			        'icon-pictures' => '<span class="icon-pictures"></span> icon-pictures',
			        'icon-video' => '<span class="icon-video"></span> icon-video',
			        'icon-camera' => '<span class="icon-camera"></span> icon-camera',
			        'icon-printer' => '<span class="icon-printer"></span> icon-printer',
			        'icon-toolbox' => '<span class="icon-toolbox"></span> icon-toolbox',
			        'icon-briefcase' => '<span class="icon-briefcase"></span> icon-briefcase',
			        'icon-wallet' => '<span class="icon-wallet"></span> icon-wallet',
			        'icon-gift' => '<span class="icon-gift"></span> icon-gift',
			        'icon-bargraph' => '<span class="icon-bargraph"></span> icon-bargraph',
			        'icon-grid' => '<span class="icon-grid"></span> icon-grid',
			        'icon-expand' => '<span class="icon-expand"></span> icon-expand',
			        'icon-focus' => '<span class="icon-focus"></span> icon-focus',
			        'icon-edit' => '<span class="icon-edit"></span> icon-edit',
			        'icon-adjustments' => '<span class="icon-adjustments"></span> icon-adjustments',
			        'icon-ribbon' => '<span class="icon-ribbon"></span> icon-ribbon',
			        'icon-hourglass' => '<span class="icon-hourglass"></span> icon-hourglass',
			        'icon-lock' => '<span class="icon-lock"></span> icon-lock',
			        'icon-megaphone' => '<span class="icon-megaphone"></span> icon-megaphone',
			        'icon-shield' => '<span class="icon-shield"></span> icon-shield',
			        'icon-trophy' => '<span class="icon-trophy"></span> icon-trophy',
			        'icon-flag' => '<span class="icon-flag"></span> icon-flag',
			        'icon-map' => '<span class="icon-map"></span> icon-map',
			        'icon-puzzle' => '<span class="icon-puzzle"></span> icon-puzzle',
			        'icon-basket' => '<span class="icon-basket"></span> icon-basket',
			        'icon-envelope' => '<span class="icon-envelope"></span> icon-envelope',
			        'icon-streetsign' => '<span class="icon-streetsign"></span> icon-streetsign',
			        'icon-telescope' => '<span class="icon-telescope"></span> icon-telescope',
			        'icon-gears' => '<span class="icon-gears"></span> icon-gears',
			        'icon-key' => '<span class="icon-key"></span> icon-key',
			        'icon-paperclip' => '<span class="icon-paperclip"></span> icon-paperclip',
			        'icon-attachment' => '<span class="icon-attachment"></span> icon-attachment',
			        'icon-pricetags' => '<span class="icon-pricetags"></span> icon-pricetags',
			        'icon-lightbulb' => '<span class="icon-lightbulb"></span> icon-lightbulb',
			        'icon-layers' => '<span class="icon-layers"></span> icon-layers',
			        'icon-pencil' => '<span class="icon-pencil"></span> icon-pencil',
			        'icon-tools' => '<span class="icon-tools"></span> icon-tools',
			        'icon-tools-2' => '<span class="icon-tools-2"></span> icon-tools-2',
			        'icon-scissors' => '<span class="icon-scissors"></span> icon-scissors',
			        'icon-paintbrush' => '<span class="icon-paintbrush"></span> icon-paintbrush',
			        'icon-magnifying-glass' => '<span class="icon-magnifying-glass"></span> icon-magnifying-glass',
			        'icon-circle-compass' => '<span class="icon-circle-compass"></span> icon-circle-compass',
			        'icon-linegraph' => '<span class="icon-linegraph"></span> icon-linegraph',
			        'icon-mic' => '<span class="icon-mic"></span> icon-mic',
			        'icon-strategy' => '<span class="icon-strategy"></span> icon-strategy',
			        'icon-beaker' => '<span class="icon-beaker"></span> icon-beaker',
			        'icon-caution' => '<span class="icon-caution"></span> icon-caution',
			        'icon-recycle' => '<span class="icon-recycle"></span> icon-recycle',
			        'icon-anchor' => '<span class="icon-anchor"></span> icon-anchor',
			        'icon-profile-male' => '<span class="icon-profile-male"></span> icon-profile-male',
			        'icon-profile-female' => '<span class="icon-profile-female"></span> icon-profile-female',
			        'icon-bike' => '<span class="icon-bike"></span> icon-bike',
			        'icon-hotairballoon' => '<span class="icon-hotairballoon"></span> icon-hotairballoon',
			        'icon-globe' => '<span class="icon-globe"></span> icon-globe',
			        'icon-genius' => '<span class="icon-genius"></span> icon-genius',
			        'icon-map-pin' => '<span class="icon-map-pin"></span> icon-map-pin',
			        'icon-dial' => '<span class="icon-dial"></span> icon-dial',
			        'icon-chat' => '<span class="icon-chat"></span> icon-chat',
			        'icon-heart' => '<span class="icon-heart"></span> icon-heart',
			        'icon-cloud' => '<span class="icon-cloud"></span> icon-cloud',
			        'icon-upload' => '<span class="icon-upload"></span> icon-upload',
			        'icon-download' => '<span class="icon-download"></span> icon-download',
			        'icon-target' => '<span class="icon-target"></span> icon-target',
			        'icon-hazardous' => '<span class="icon-hazardous"></span> icon-hazardous',
			        'icon-piechart' => '<span class="icon-piechart"></span> icon-piechart',
			        'icon-speedometer' => '<span class="icon-speedometer"></span> icon-speedometer',
			        'icon-global' => '<span class="icon-global"></span> icon-global',
			        'icon-compass' => '<span class="icon-compass"></span> icon-compass',
			        'icon-lifesaver' => '<span class="icon-lifesaver"></span> icon-lifesaver',
			        'icon-clock' => '<span class="icon-clock"></span> icon-clock',
			        'icon-aperture' => '<span class="icon-aperture"></span> icon-aperture',
			        'icon-quote' => '<span class="icon-quote"></span> icon-quote',
			        'icon-scope' => '<span class="icon-scope"></span> icon-scope',
			        'icon-alarmclock' => '<span class="icon-alarmclock"></span> icon-alarmclock',
			        'icon-refresh' => '<span class="icon-refresh"></span> icon-refresh',
			        'icon-happy' => '<span class="icon-happy"></span> icon-happy',
			        'icon-sad' => '<span class="icon-sad"></span> icon-sad',
			        'icon-facebook' => '<span class="icon-facebook"></span> icon-facebook',
			        'icon-twitter' => '<span class="icon-twitter"></span> icon-twitter',
			        'icon-googleplus' => '<span class="icon-googleplus"></span> icon-googleplus',
			        'icon-rss' => '<span class="icon-rss"></span> icon-rss',
			        'icon-tumblr' => '<span class="icon-tumblr"></span> icon-tumblr',
			        'icon-linkedin' => '<span class="icon-linkedin"></span> icon-linkedin',
			        'icon-dribbble' => '<span class="icon-dribbble"></span> icon-dribbble',
		        ),
		        'default'  => 'icon-lifesaver',
	        ),
	        array(
		        'id'       => 'home-service-three-description',
		        'type'     => 'textarea',
		        'title'    => __( 'Service Three Description', 'hola' ),
		        'desc'     => __( 'Please input the service description.', 'hola' ),
		        'default'  => 'Then came the night of the first falling star. She stared through the window at the stars. I watched the storm so beautiful yet terrific.',
	        ),
	        
	        array(
                'id'       => 'home-service-four-title',
                'type'     => 'text',
                'title'    => __( 'Service Four Title', 'hola' ),
                'desc'     => __( 'Please input the service title.', 'hola' ),
                'default'  => 'PHOTOGRAPHY',
            ),
	        array(
		        'id'       => 'home-service-four-icon',
		        'type'     => 'select',
		        'title'    => __('Select Service Icon', 'hola'),
		        'desc'     => __('Please selec service icon from the list.', 'hola').' <a href="http://rhythm.nikadevs.com/content/icons-et-line">Full list</a>.',
		        // Must provide key => value pairs for select options
		        'options'  => array(
			        'icon-mobile' => '<span class="icon-mobile"></span> icon-mobile',
			        'icon-laptop' => '<span class="icon-laptop"></span> icon-laptop',
			        'icon-desktop' => '<span class="icon-desktop"></span> icon-desktop',
			        'icon-tablet' => '<span class="icon-tablet"></span> icon-tablet',
			        'icon-phone' => '<span class="icon-phone"></span> icon-phone',
			        'icon-document' => '<span class="icon-document"></span> icon-document',
			        'icon-documents' => '<span class="icon-documents"></span> icon-documents',
			        'icon-search' => '<span class="icon-search"></span> icon-search',
			        'icon-clipboard' => '<span class="icon-clipboard"></span> icon-clipboard',
			        'icon-newspaper' => '<span class="icon-newspaper"></span> icon-newspaper',
			        'icon-notebook' => '<span class="icon-notebook"></span> icon-notebook',
			        'icon-book-open' => '<span class="icon-book-open"></span> icon-book-open',
			        'icon-browser' => '<span class="icon-browser"></span> icon-browser',
			        'icon-calendar' => '<span class="icon-calendar"></span> icon-calendar',
			        'icon-presentation' => '<span class="icon-presentation"></span> icon-presentation',
			        'icon-picture' => '<span class="icon-picture"></span> icon-picture',
			        'icon-pictures' => '<span class="icon-pictures"></span> icon-pictures',
			        'icon-video' => '<span class="icon-video"></span> icon-video',
			        'icon-camera' => '<span class="icon-camera"></span> icon-camera',
			        'icon-printer' => '<span class="icon-printer"></span> icon-printer',
			        'icon-toolbox' => '<span class="icon-toolbox"></span> icon-toolbox',
			        'icon-briefcase' => '<span class="icon-briefcase"></span> icon-briefcase',
			        'icon-wallet' => '<span class="icon-wallet"></span> icon-wallet',
			        'icon-gift' => '<span class="icon-gift"></span> icon-gift',
			        'icon-bargraph' => '<span class="icon-bargraph"></span> icon-bargraph',
			        'icon-grid' => '<span class="icon-grid"></span> icon-grid',
			        'icon-expand' => '<span class="icon-expand"></span> icon-expand',
			        'icon-focus' => '<span class="icon-focus"></span> icon-focus',
			        'icon-edit' => '<span class="icon-edit"></span> icon-edit',
			        'icon-adjustments' => '<span class="icon-adjustments"></span> icon-adjustments',
			        'icon-ribbon' => '<span class="icon-ribbon"></span> icon-ribbon',
			        'icon-hourglass' => '<span class="icon-hourglass"></span> icon-hourglass',
			        'icon-lock' => '<span class="icon-lock"></span> icon-lock',
			        'icon-megaphone' => '<span class="icon-megaphone"></span> icon-megaphone',
			        'icon-shield' => '<span class="icon-shield"></span> icon-shield',
			        'icon-trophy' => '<span class="icon-trophy"></span> icon-trophy',
			        'icon-flag' => '<span class="icon-flag"></span> icon-flag',
			        'icon-map' => '<span class="icon-map"></span> icon-map',
			        'icon-puzzle' => '<span class="icon-puzzle"></span> icon-puzzle',
			        'icon-basket' => '<span class="icon-basket"></span> icon-basket',
			        'icon-envelope' => '<span class="icon-envelope"></span> icon-envelope',
			        'icon-streetsign' => '<span class="icon-streetsign"></span> icon-streetsign',
			        'icon-telescope' => '<span class="icon-telescope"></span> icon-telescope',
			        'icon-gears' => '<span class="icon-gears"></span> icon-gears',
			        'icon-key' => '<span class="icon-key"></span> icon-key',
			        'icon-paperclip' => '<span class="icon-paperclip"></span> icon-paperclip',
			        'icon-attachment' => '<span class="icon-attachment"></span> icon-attachment',
			        'icon-pricetags' => '<span class="icon-pricetags"></span> icon-pricetags',
			        'icon-lightbulb' => '<span class="icon-lightbulb"></span> icon-lightbulb',
			        'icon-layers' => '<span class="icon-layers"></span> icon-layers',
			        'icon-pencil' => '<span class="icon-pencil"></span> icon-pencil',
			        'icon-tools' => '<span class="icon-tools"></span> icon-tools',
			        'icon-tools-2' => '<span class="icon-tools-2"></span> icon-tools-2',
			        'icon-scissors' => '<span class="icon-scissors"></span> icon-scissors',
			        'icon-paintbrush' => '<span class="icon-paintbrush"></span> icon-paintbrush',
			        'icon-magnifying-glass' => '<span class="icon-magnifying-glass"></span> icon-magnifying-glass',
			        'icon-circle-compass' => '<span class="icon-circle-compass"></span> icon-circle-compass',
			        'icon-linegraph' => '<span class="icon-linegraph"></span> icon-linegraph',
			        'icon-mic' => '<span class="icon-mic"></span> icon-mic',
			        'icon-strategy' => '<span class="icon-strategy"></span> icon-strategy',
			        'icon-beaker' => '<span class="icon-beaker"></span> icon-beaker',
			        'icon-caution' => '<span class="icon-caution"></span> icon-caution',
			        'icon-recycle' => '<span class="icon-recycle"></span> icon-recycle',
			        'icon-anchor' => '<span class="icon-anchor"></span> icon-anchor',
			        'icon-profile-male' => '<span class="icon-profile-male"></span> icon-profile-male',
			        'icon-profile-female' => '<span class="icon-profile-female"></span> icon-profile-female',
			        'icon-bike' => '<span class="icon-bike"></span> icon-bike',
			        'icon-hotairballoon' => '<span class="icon-hotairballoon"></span> icon-hotairballoon',
			        'icon-globe' => '<span class="icon-globe"></span> icon-globe',
			        'icon-genius' => '<span class="icon-genius"></span> icon-genius',
			        'icon-map-pin' => '<span class="icon-map-pin"></span> icon-map-pin',
			        'icon-dial' => '<span class="icon-dial"></span> icon-dial',
			        'icon-chat' => '<span class="icon-chat"></span> icon-chat',
			        'icon-heart' => '<span class="icon-heart"></span> icon-heart',
			        'icon-cloud' => '<span class="icon-cloud"></span> icon-cloud',
			        'icon-upload' => '<span class="icon-upload"></span> icon-upload',
			        'icon-download' => '<span class="icon-download"></span> icon-download',
			        'icon-target' => '<span class="icon-target"></span> icon-target',
			        'icon-hazardous' => '<span class="icon-hazardous"></span> icon-hazardous',
			        'icon-piechart' => '<span class="icon-piechart"></span> icon-piechart',
			        'icon-speedometer' => '<span class="icon-speedometer"></span> icon-speedometer',
			        'icon-global' => '<span class="icon-global"></span> icon-global',
			        'icon-compass' => '<span class="icon-compass"></span> icon-compass',
			        'icon-lifesaver' => '<span class="icon-lifesaver"></span> icon-lifesaver',
			        'icon-clock' => '<span class="icon-clock"></span> icon-clock',
			        'icon-aperture' => '<span class="icon-aperture"></span> icon-aperture',
			        'icon-quote' => '<span class="icon-quote"></span> icon-quote',
			        'icon-scope' => '<span class="icon-scope"></span> icon-scope',
			        'icon-alarmclock' => '<span class="icon-alarmclock"></span> icon-alarmclock',
			        'icon-refresh' => '<span class="icon-refresh"></span> icon-refresh',
			        'icon-happy' => '<span class="icon-happy"></span> icon-happy',
			        'icon-sad' => '<span class="icon-sad"></span> icon-sad',
			        'icon-facebook' => '<span class="icon-facebook"></span> icon-facebook',
			        'icon-twitter' => '<span class="icon-twitter"></span> icon-twitter',
			        'icon-googleplus' => '<span class="icon-googleplus"></span> icon-googleplus',
			        'icon-rss' => '<span class="icon-rss"></span> icon-rss',
			        'icon-tumblr' => '<span class="icon-tumblr"></span> icon-tumblr',
			        'icon-linkedin' => '<span class="icon-linkedin"></span> icon-linkedin',
			        'icon-dribbble' => '<span class="icon-dribbble"></span> icon-dribbble',
		        ),
		        'default'  => 'icon-camera',
	        ),
	        array(
		        'id'       => 'home-service-four-description',
		        'type'     => 'textarea',
		        'title'    => __( 'Service Four Description', 'hola' ),
		        'desc'     => __( 'Please input the service description.', 'hola' ),
		        'default'  => 'Then came the night of the first falling star. She stared through the window at the stars. I watched the storm so beautiful yet terrific.',
	        ),
	        
	        array(
                'id'       => 'home-service-five-title',
                'type'     => 'text',
                'title'    => __( 'Service Five Title', 'hola' ),
                'desc'     => __( 'Please input the service title.', 'hola' ),
                'default'  => 'BRANDING DESIGN',
            ),
	        array(
		        'id'       => 'home-service-five-icon',
		        'type'     => 'select',
		        'title'    => __('Select Service Icon', 'hola'),
		        'desc'     => __('Please selec service icon from the list.', 'hola').' <a href="http://rhythm.nikadevs.com/content/icons-et-line">Full list</a>.',
		        // Must provide key => value pairs for select options
		        'options'  => array(
			        'icon-mobile' => '<span class="icon-mobile"></span> icon-mobile',
			        'icon-laptop' => '<span class="icon-laptop"></span> icon-laptop',
			        'icon-desktop' => '<span class="icon-desktop"></span> icon-desktop',
			        'icon-tablet' => '<span class="icon-tablet"></span> icon-tablet',
			        'icon-phone' => '<span class="icon-phone"></span> icon-phone',
			        'icon-document' => '<span class="icon-document"></span> icon-document',
			        'icon-documents' => '<span class="icon-documents"></span> icon-documents',
			        'icon-search' => '<span class="icon-search"></span> icon-search',
			        'icon-clipboard' => '<span class="icon-clipboard"></span> icon-clipboard',
			        'icon-newspaper' => '<span class="icon-newspaper"></span> icon-newspaper',
			        'icon-notebook' => '<span class="icon-notebook"></span> icon-notebook',
			        'icon-book-open' => '<span class="icon-book-open"></span> icon-book-open',
			        'icon-browser' => '<span class="icon-browser"></span> icon-browser',
			        'icon-calendar' => '<span class="icon-calendar"></span> icon-calendar',
			        'icon-presentation' => '<span class="icon-presentation"></span> icon-presentation',
			        'icon-picture' => '<span class="icon-picture"></span> icon-picture',
			        'icon-pictures' => '<span class="icon-pictures"></span> icon-pictures',
			        'icon-video' => '<span class="icon-video"></span> icon-video',
			        'icon-camera' => '<span class="icon-camera"></span> icon-camera',
			        'icon-printer' => '<span class="icon-printer"></span> icon-printer',
			        'icon-toolbox' => '<span class="icon-toolbox"></span> icon-toolbox',
			        'icon-briefcase' => '<span class="icon-briefcase"></span> icon-briefcase',
			        'icon-wallet' => '<span class="icon-wallet"></span> icon-wallet',
			        'icon-gift' => '<span class="icon-gift"></span> icon-gift',
			        'icon-bargraph' => '<span class="icon-bargraph"></span> icon-bargraph',
			        'icon-grid' => '<span class="icon-grid"></span> icon-grid',
			        'icon-expand' => '<span class="icon-expand"></span> icon-expand',
			        'icon-focus' => '<span class="icon-focus"></span> icon-focus',
			        'icon-edit' => '<span class="icon-edit"></span> icon-edit',
			        'icon-adjustments' => '<span class="icon-adjustments"></span> icon-adjustments',
			        'icon-ribbon' => '<span class="icon-ribbon"></span> icon-ribbon',
			        'icon-hourglass' => '<span class="icon-hourglass"></span> icon-hourglass',
			        'icon-lock' => '<span class="icon-lock"></span> icon-lock',
			        'icon-megaphone' => '<span class="icon-megaphone"></span> icon-megaphone',
			        'icon-shield' => '<span class="icon-shield"></span> icon-shield',
			        'icon-trophy' => '<span class="icon-trophy"></span> icon-trophy',
			        'icon-flag' => '<span class="icon-flag"></span> icon-flag',
			        'icon-map' => '<span class="icon-map"></span> icon-map',
			        'icon-puzzle' => '<span class="icon-puzzle"></span> icon-puzzle',
			        'icon-basket' => '<span class="icon-basket"></span> icon-basket',
			        'icon-envelope' => '<span class="icon-envelope"></span> icon-envelope',
			        'icon-streetsign' => '<span class="icon-streetsign"></span> icon-streetsign',
			        'icon-telescope' => '<span class="icon-telescope"></span> icon-telescope',
			        'icon-gears' => '<span class="icon-gears"></span> icon-gears',
			        'icon-key' => '<span class="icon-key"></span> icon-key',
			        'icon-paperclip' => '<span class="icon-paperclip"></span> icon-paperclip',
			        'icon-attachment' => '<span class="icon-attachment"></span> icon-attachment',
			        'icon-pricetags' => '<span class="icon-pricetags"></span> icon-pricetags',
			        'icon-lightbulb' => '<span class="icon-lightbulb"></span> icon-lightbulb',
			        'icon-layers' => '<span class="icon-layers"></span> icon-layers',
			        'icon-pencil' => '<span class="icon-pencil"></span> icon-pencil',
			        'icon-tools' => '<span class="icon-tools"></span> icon-tools',
			        'icon-tools-2' => '<span class="icon-tools-2"></span> icon-tools-2',
			        'icon-scissors' => '<span class="icon-scissors"></span> icon-scissors',
			        'icon-paintbrush' => '<span class="icon-paintbrush"></span> icon-paintbrush',
			        'icon-magnifying-glass' => '<span class="icon-magnifying-glass"></span> icon-magnifying-glass',
			        'icon-circle-compass' => '<span class="icon-circle-compass"></span> icon-circle-compass',
			        'icon-linegraph' => '<span class="icon-linegraph"></span> icon-linegraph',
			        'icon-mic' => '<span class="icon-mic"></span> icon-mic',
			        'icon-strategy' => '<span class="icon-strategy"></span> icon-strategy',
			        'icon-beaker' => '<span class="icon-beaker"></span> icon-beaker',
			        'icon-caution' => '<span class="icon-caution"></span> icon-caution',
			        'icon-recycle' => '<span class="icon-recycle"></span> icon-recycle',
			        'icon-anchor' => '<span class="icon-anchor"></span> icon-anchor',
			        'icon-profile-male' => '<span class="icon-profile-male"></span> icon-profile-male',
			        'icon-profile-female' => '<span class="icon-profile-female"></span> icon-profile-female',
			        'icon-bike' => '<span class="icon-bike"></span> icon-bike',
			        'icon-hotairballoon' => '<span class="icon-hotairballoon"></span> icon-hotairballoon',
			        'icon-globe' => '<span class="icon-globe"></span> icon-globe',
			        'icon-genius' => '<span class="icon-genius"></span> icon-genius',
			        'icon-map-pin' => '<span class="icon-map-pin"></span> icon-map-pin',
			        'icon-dial' => '<span class="icon-dial"></span> icon-dial',
			        'icon-chat' => '<span class="icon-chat"></span> icon-chat',
			        'icon-heart' => '<span class="icon-heart"></span> icon-heart',
			        'icon-cloud' => '<span class="icon-cloud"></span> icon-cloud',
			        'icon-upload' => '<span class="icon-upload"></span> icon-upload',
			        'icon-download' => '<span class="icon-download"></span> icon-download',
			        'icon-target' => '<span class="icon-target"></span> icon-target',
			        'icon-hazardous' => '<span class="icon-hazardous"></span> icon-hazardous',
			        'icon-piechart' => '<span class="icon-piechart"></span> icon-piechart',
			        'icon-speedometer' => '<span class="icon-speedometer"></span> icon-speedometer',
			        'icon-global' => '<span class="icon-global"></span> icon-global',
			        'icon-compass' => '<span class="icon-compass"></span> icon-compass',
			        'icon-lifesaver' => '<span class="icon-lifesaver"></span> icon-lifesaver',
			        'icon-clock' => '<span class="icon-clock"></span> icon-clock',
			        'icon-aperture' => '<span class="icon-aperture"></span> icon-aperture',
			        'icon-quote' => '<span class="icon-quote"></span> icon-quote',
			        'icon-scope' => '<span class="icon-scope"></span> icon-scope',
			        'icon-alarmclock' => '<span class="icon-alarmclock"></span> icon-alarmclock',
			        'icon-refresh' => '<span class="icon-refresh"></span> icon-refresh',
			        'icon-happy' => '<span class="icon-happy"></span> icon-happy',
			        'icon-sad' => '<span class="icon-sad"></span> icon-sad',
			        'icon-facebook' => '<span class="icon-facebook"></span> icon-facebook',
			        'icon-twitter' => '<span class="icon-twitter"></span> icon-twitter',
			        'icon-googleplus' => '<span class="icon-googleplus"></span> icon-googleplus',
			        'icon-rss' => '<span class="icon-rss"></span> icon-rss',
			        'icon-tumblr' => '<span class="icon-tumblr"></span> icon-tumblr',
			        'icon-linkedin' => '<span class="icon-linkedin"></span> icon-linkedin',
			        'icon-dribbble' => '<span class="icon-dribbble"></span> icon-dribbble',
		        ),
		        'default'  => 'icon-gears',
	        ),
	        array(
		        'id'       => 'home-service-five-description',
		        'type'     => 'textarea',
		        'title'    => __( 'Service Five Description', 'hola' ),
		        'desc'     => __( 'Please input the service description.', 'hola' ),
		        'default'  => 'Then came the night of the first falling star. She stared through the window at the stars. I watched the storm so beautiful yet terrific.',
	        ),
	        
	        array(
                'id'       => 'home-service-six-title',
                'type'     => 'text',
                'title'    => __( 'Service Six Title', 'hola' ),
                'desc'     => __( 'Please input the service title.', 'hola' ),
                'default'  => 'OUR SUPPORT',
            ),
	        array(
		        'id'       => 'home-service-six-icon',
		        'type'     => 'select',
		        'title'    => __('Select Service Icon', 'hola'),
		        'desc'     => __('Please selec service icon from the list.', 'hola').' <a href="http://rhythm.nikadevs.com/content/icons-et-line">Full list</a>.',
		        // Must provide key => value pairs for select options
		        'options'  => array(
			        'icon-mobile' => '<span class="icon-mobile"></span> icon-mobile',
			        'icon-laptop' => '<span class="icon-laptop"></span> icon-laptop',
			        'icon-desktop' => '<span class="icon-desktop"></span> icon-desktop',
			        'icon-tablet' => '<span class="icon-tablet"></span> icon-tablet',
			        'icon-phone' => '<span class="icon-phone"></span> icon-phone',
			        'icon-document' => '<span class="icon-document"></span> icon-document',
			        'icon-documents' => '<span class="icon-documents"></span> icon-documents',
			        'icon-search' => '<span class="icon-search"></span> icon-search',
			        'icon-clipboard' => '<span class="icon-clipboard"></span> icon-clipboard',
			        'icon-newspaper' => '<span class="icon-newspaper"></span> icon-newspaper',
			        'icon-notebook' => '<span class="icon-notebook"></span> icon-notebook',
			        'icon-book-open' => '<span class="icon-book-open"></span> icon-book-open',
			        'icon-browser' => '<span class="icon-browser"></span> icon-browser',
			        'icon-calendar' => '<span class="icon-calendar"></span> icon-calendar',
			        'icon-presentation' => '<span class="icon-presentation"></span> icon-presentation',
			        'icon-picture' => '<span class="icon-picture"></span> icon-picture',
			        'icon-pictures' => '<span class="icon-pictures"></span> icon-pictures',
			        'icon-video' => '<span class="icon-video"></span> icon-video',
			        'icon-camera' => '<span class="icon-camera"></span> icon-camera',
			        'icon-printer' => '<span class="icon-printer"></span> icon-printer',
			        'icon-toolbox' => '<span class="icon-toolbox"></span> icon-toolbox',
			        'icon-briefcase' => '<span class="icon-briefcase"></span> icon-briefcase',
			        'icon-wallet' => '<span class="icon-wallet"></span> icon-wallet',
			        'icon-gift' => '<span class="icon-gift"></span> icon-gift',
			        'icon-bargraph' => '<span class="icon-bargraph"></span> icon-bargraph',
			        'icon-grid' => '<span class="icon-grid"></span> icon-grid',
			        'icon-expand' => '<span class="icon-expand"></span> icon-expand',
			        'icon-focus' => '<span class="icon-focus"></span> icon-focus',
			        'icon-edit' => '<span class="icon-edit"></span> icon-edit',
			        'icon-adjustments' => '<span class="icon-adjustments"></span> icon-adjustments',
			        'icon-ribbon' => '<span class="icon-ribbon"></span> icon-ribbon',
			        'icon-hourglass' => '<span class="icon-hourglass"></span> icon-hourglass',
			        'icon-lock' => '<span class="icon-lock"></span> icon-lock',
			        'icon-megaphone' => '<span class="icon-megaphone"></span> icon-megaphone',
			        'icon-shield' => '<span class="icon-shield"></span> icon-shield',
			        'icon-trophy' => '<span class="icon-trophy"></span> icon-trophy',
			        'icon-flag' => '<span class="icon-flag"></span> icon-flag',
			        'icon-map' => '<span class="icon-map"></span> icon-map',
			        'icon-puzzle' => '<span class="icon-puzzle"></span> icon-puzzle',
			        'icon-basket' => '<span class="icon-basket"></span> icon-basket',
			        'icon-envelope' => '<span class="icon-envelope"></span> icon-envelope',
			        'icon-streetsign' => '<span class="icon-streetsign"></span> icon-streetsign',
			        'icon-telescope' => '<span class="icon-telescope"></span> icon-telescope',
			        'icon-gears' => '<span class="icon-gears"></span> icon-gears',
			        'icon-key' => '<span class="icon-key"></span> icon-key',
			        'icon-paperclip' => '<span class="icon-paperclip"></span> icon-paperclip',
			        'icon-attachment' => '<span class="icon-attachment"></span> icon-attachment',
			        'icon-pricetags' => '<span class="icon-pricetags"></span> icon-pricetags',
			        'icon-lightbulb' => '<span class="icon-lightbulb"></span> icon-lightbulb',
			        'icon-layers' => '<span class="icon-layers"></span> icon-layers',
			        'icon-pencil' => '<span class="icon-pencil"></span> icon-pencil',
			        'icon-tools' => '<span class="icon-tools"></span> icon-tools',
			        'icon-tools-2' => '<span class="icon-tools-2"></span> icon-tools-2',
			        'icon-scissors' => '<span class="icon-scissors"></span> icon-scissors',
			        'icon-paintbrush' => '<span class="icon-paintbrush"></span> icon-paintbrush',
			        'icon-magnifying-glass' => '<span class="icon-magnifying-glass"></span> icon-magnifying-glass',
			        'icon-circle-compass' => '<span class="icon-circle-compass"></span> icon-circle-compass',
			        'icon-linegraph' => '<span class="icon-linegraph"></span> icon-linegraph',
			        'icon-mic' => '<span class="icon-mic"></span> icon-mic',
			        'icon-strategy' => '<span class="icon-strategy"></span> icon-strategy',
			        'icon-beaker' => '<span class="icon-beaker"></span> icon-beaker',
			        'icon-caution' => '<span class="icon-caution"></span> icon-caution',
			        'icon-recycle' => '<span class="icon-recycle"></span> icon-recycle',
			        'icon-anchor' => '<span class="icon-anchor"></span> icon-anchor',
			        'icon-profile-male' => '<span class="icon-profile-male"></span> icon-profile-male',
			        'icon-profile-female' => '<span class="icon-profile-female"></span> icon-profile-female',
			        'icon-bike' => '<span class="icon-bike"></span> icon-bike',
			        'icon-hotairballoon' => '<span class="icon-hotairballoon"></span> icon-hotairballoon',
			        'icon-globe' => '<span class="icon-globe"></span> icon-globe',
			        'icon-genius' => '<span class="icon-genius"></span> icon-genius',
			        'icon-map-pin' => '<span class="icon-map-pin"></span> icon-map-pin',
			        'icon-dial' => '<span class="icon-dial"></span> icon-dial',
			        'icon-chat' => '<span class="icon-chat"></span> icon-chat',
			        'icon-heart' => '<span class="icon-heart"></span> icon-heart',
			        'icon-cloud' => '<span class="icon-cloud"></span> icon-cloud',
			        'icon-upload' => '<span class="icon-upload"></span> icon-upload',
			        'icon-download' => '<span class="icon-download"></span> icon-download',
			        'icon-target' => '<span class="icon-target"></span> icon-target',
			        'icon-hazardous' => '<span class="icon-hazardous"></span> icon-hazardous',
			        'icon-piechart' => '<span class="icon-piechart"></span> icon-piechart',
			        'icon-speedometer' => '<span class="icon-speedometer"></span> icon-speedometer',
			        'icon-global' => '<span class="icon-global"></span> icon-global',
			        'icon-compass' => '<span class="icon-compass"></span> icon-compass',
			        'icon-lifesaver' => '<span class="icon-lifesaver"></span> icon-lifesaver',
			        'icon-clock' => '<span class="icon-clock"></span> icon-clock',
			        'icon-aperture' => '<span class="icon-aperture"></span> icon-aperture',
			        'icon-quote' => '<span class="icon-quote"></span> icon-quote',
			        'icon-scope' => '<span class="icon-scope"></span> icon-scope',
			        'icon-alarmclock' => '<span class="icon-alarmclock"></span> icon-alarmclock',
			        'icon-refresh' => '<span class="icon-refresh"></span> icon-refresh',
			        'icon-happy' => '<span class="icon-happy"></span> icon-happy',
			        'icon-sad' => '<span class="icon-sad"></span> icon-sad',
			        'icon-facebook' => '<span class="icon-facebook"></span> icon-facebook',
			        'icon-twitter' => '<span class="icon-twitter"></span> icon-twitter',
			        'icon-googleplus' => '<span class="icon-googleplus"></span> icon-googleplus',
			        'icon-rss' => '<span class="icon-rss"></span> icon-rss',
			        'icon-tumblr' => '<span class="icon-tumblr"></span> icon-tumblr',
			        'icon-linkedin' => '<span class="icon-linkedin"></span> icon-linkedin',
			        'icon-dribbble' => '<span class="icon-dribbble"></span> icon-dribbble',
		        ),
		        'default'  => 'icon-pricetags',
	        ),
	        array(
		        'id'       => 'home-service-six-description',
		        'type'     => 'textarea',
		        'title'    => __( 'Service Six Description', 'hola' ),
		        'desc'     => __( 'Please input the service description.', 'hola' ),
		        'default'  => 'Then came the night of the first falling star. She stared through the window at the stars. I watched the storm so beautiful yet terrific.',
	        ),
	        
        )
    ) );

	
	Redux::setSection( $opt_name, array(
		'title'      => __( 'Work Process Section', 'hola' ),
		'desc'       => __( 'Settings for work process section.', 'hola' ),
		'id'         => 'home-work',
		'subsection' => true,
		'fields'     => array(
			array(
				'id'       => 'home-work-heading',
				'type'     => 'text',
				'title'    => __( 'Work Process Section Heading', 'hola' ),
				'desc'     => __( 'Please input the section title.', 'hola' ),
				'default'  => 'WORK PROCESS',
			),
			array(
				'id'       => 'home-work-description',
				'type'     => 'textarea',
				'title'    => __( 'Work Process Section Description', 'hola' ),
				'desc'     => __( 'Please input the section description.', 'hola' ),
				'default'  => 'All their equipment and instruments are alive. I watched the beautiful yet terrific. Silver mist suffused the deck of the ship. The recorded scratched speaker.Almost before we knew it.',
			),
			array(
				'id'       => 'home-work-process-1-title',
				'type'     => 'text',
				'title'    => __( 'Work Process One Heading', 'hola' ),
				'desc'     => __( 'Please input the process title.', 'hola' ),
				'default'  => '01 DESIGN',
			),
			
			array(
				'id'       => 'home-work-process-1-icon',
				'type'     => 'select',
				'title'    => __('Select Process Icon', 'hola'),
				'desc'     => __('Please select process icon from the list.', 'hola').' <a href="http://rhythm.nikadevs.com/content/icons-et-line">Full list</a>.',
				// Must provide key => value pairs for select options
				'options'  => array(
					'icon-mobile' => '<span class="icon-mobile"></span> icon-mobile',
					'icon-laptop' => '<span class="icon-laptop"></span> icon-laptop',
					'icon-desktop' => '<span class="icon-desktop"></span> icon-desktop',
					'icon-tablet' => '<span class="icon-tablet"></span> icon-tablet',
					'icon-phone' => '<span class="icon-phone"></span> icon-phone',
					'icon-document' => '<span class="icon-document"></span> icon-document',
					'icon-documents' => '<span class="icon-documents"></span> icon-documents',
					'icon-search' => '<span class="icon-search"></span> icon-search',
					'icon-clipboard' => '<span class="icon-clipboard"></span> icon-clipboard',
					'icon-newspaper' => '<span class="icon-newspaper"></span> icon-newspaper',
					'icon-notebook' => '<span class="icon-notebook"></span> icon-notebook',
					'icon-book-open' => '<span class="icon-book-open"></span> icon-book-open',
					'icon-browser' => '<span class="icon-browser"></span> icon-browser',
					'icon-calendar' => '<span class="icon-calendar"></span> icon-calendar',
					'icon-presentation' => '<span class="icon-presentation"></span> icon-presentation',
					'icon-picture' => '<span class="icon-picture"></span> icon-picture',
					'icon-pictures' => '<span class="icon-pictures"></span> icon-pictures',
					'icon-video' => '<span class="icon-video"></span> icon-video',
					'icon-camera' => '<span class="icon-camera"></span> icon-camera',
					'icon-printer' => '<span class="icon-printer"></span> icon-printer',
					'icon-toolbox' => '<span class="icon-toolbox"></span> icon-toolbox',
					'icon-briefcase' => '<span class="icon-briefcase"></span> icon-briefcase',
					'icon-wallet' => '<span class="icon-wallet"></span> icon-wallet',
					'icon-gift' => '<span class="icon-gift"></span> icon-gift',
					'icon-bargraph' => '<span class="icon-bargraph"></span> icon-bargraph',
					'icon-grid' => '<span class="icon-grid"></span> icon-grid',
					'icon-expand' => '<span class="icon-expand"></span> icon-expand',
					'icon-focus' => '<span class="icon-focus"></span> icon-focus',
					'icon-edit' => '<span class="icon-edit"></span> icon-edit',
					'icon-adjustments' => '<span class="icon-adjustments"></span> icon-adjustments',
					'icon-ribbon' => '<span class="icon-ribbon"></span> icon-ribbon',
					'icon-hourglass' => '<span class="icon-hourglass"></span> icon-hourglass',
					'icon-lock' => '<span class="icon-lock"></span> icon-lock',
					'icon-megaphone' => '<span class="icon-megaphone"></span> icon-megaphone',
					'icon-shield' => '<span class="icon-shield"></span> icon-shield',
					'icon-trophy' => '<span class="icon-trophy"></span> icon-trophy',
					'icon-flag' => '<span class="icon-flag"></span> icon-flag',
					'icon-map' => '<span class="icon-map"></span> icon-map',
					'icon-puzzle' => '<span class="icon-puzzle"></span> icon-puzzle',
					'icon-basket' => '<span class="icon-basket"></span> icon-basket',
					'icon-envelope' => '<span class="icon-envelope"></span> icon-envelope',
					'icon-streetsign' => '<span class="icon-streetsign"></span> icon-streetsign',
					'icon-telescope' => '<span class="icon-telescope"></span> icon-telescope',
					'icon-gears' => '<span class="icon-gears"></span> icon-gears',
					'icon-key' => '<span class="icon-key"></span> icon-key',
					'icon-paperclip' => '<span class="icon-paperclip"></span> icon-paperclip',
					'icon-attachment' => '<span class="icon-attachment"></span> icon-attachment',
					'icon-pricetags' => '<span class="icon-pricetags"></span> icon-pricetags',
					'icon-lightbulb' => '<span class="icon-lightbulb"></span> icon-lightbulb',
					'icon-layers' => '<span class="icon-layers"></span> icon-layers',
					'icon-pencil' => '<span class="icon-pencil"></span> icon-pencil',
					'icon-tools' => '<span class="icon-tools"></span> icon-tools',
					'icon-tools-2' => '<span class="icon-tools-2"></span> icon-tools-2',
					'icon-scissors' => '<span class="icon-scissors"></span> icon-scissors',
					'icon-paintbrush' => '<span class="icon-paintbrush"></span> icon-paintbrush',
					'icon-magnifying-glass' => '<span class="icon-magnifying-glass"></span> icon-magnifying-glass',
					'icon-circle-compass' => '<span class="icon-circle-compass"></span> icon-circle-compass',
					'icon-linegraph' => '<span class="icon-linegraph"></span> icon-linegraph',
					'icon-mic' => '<span class="icon-mic"></span> icon-mic',
					'icon-strategy' => '<span class="icon-strategy"></span> icon-strategy',
					'icon-beaker' => '<span class="icon-beaker"></span> icon-beaker',
					'icon-caution' => '<span class="icon-caution"></span> icon-caution',
					'icon-recycle' => '<span class="icon-recycle"></span> icon-recycle',
					'icon-anchor' => '<span class="icon-anchor"></span> icon-anchor',
					'icon-profile-male' => '<span class="icon-profile-male"></span> icon-profile-male',
					'icon-profile-female' => '<span class="icon-profile-female"></span> icon-profile-female',
					'icon-bike' => '<span class="icon-bike"></span> icon-bike',
					'icon-hotairballoon' => '<span class="icon-hotairballoon"></span> icon-hotairballoon',
					'icon-globe' => '<span class="icon-globe"></span> icon-globe',
					'icon-genius' => '<span class="icon-genius"></span> icon-genius',
					'icon-map-pin' => '<span class="icon-map-pin"></span> icon-map-pin',
					'icon-dial' => '<span class="icon-dial"></span> icon-dial',
					'icon-chat' => '<span class="icon-chat"></span> icon-chat',
					'icon-heart' => '<span class="icon-heart"></span> icon-heart',
					'icon-cloud' => '<span class="icon-cloud"></span> icon-cloud',
					'icon-upload' => '<span class="icon-upload"></span> icon-upload',
					'icon-download' => '<span class="icon-download"></span> icon-download',
					'icon-target' => '<span class="icon-target"></span> icon-target',
					'icon-hazardous' => '<span class="icon-hazardous"></span> icon-hazardous',
					'icon-piechart' => '<span class="icon-piechart"></span> icon-piechart',
					'icon-speedometer' => '<span class="icon-speedometer"></span> icon-speedometer',
					'icon-global' => '<span class="icon-global"></span> icon-global',
					'icon-compass' => '<span class="icon-compass"></span> icon-compass',
					'icon-lifesaver' => '<span class="icon-lifesaver"></span> icon-lifesaver',
					'icon-clock' => '<span class="icon-clock"></span> icon-clock',
					'icon-aperture' => '<span class="icon-aperture"></span> icon-aperture',
					'icon-quote' => '<span class="icon-quote"></span> icon-quote',
					'icon-scope' => '<span class="icon-scope"></span> icon-scope',
					'icon-alarmclock' => '<span class="icon-alarmclock"></span> icon-alarmclock',
					'icon-refresh' => '<span class="icon-refresh"></span> icon-refresh',
					'icon-happy' => '<span class="icon-happy"></span> icon-happy',
					'icon-sad' => '<span class="icon-sad"></span> icon-sad',
					'icon-facebook' => '<span class="icon-facebook"></span> icon-facebook',
					'icon-twitter' => '<span class="icon-twitter"></span> icon-twitter',
					'icon-googleplus' => '<span class="icon-googleplus"></span> icon-googleplus',
					'icon-rss' => '<span class="icon-rss"></span> icon-rss',
					'icon-tumblr' => '<span class="icon-tumblr"></span> icon-tumblr',
					'icon-linkedin' => '<span class="icon-linkedin"></span> icon-linkedin',
					'icon-dribbble' => '<span class="icon-dribbble"></span> icon-dribbble',
				),
				'default'  => 'icon-laptop',
			),
			array(
				'id'       => 'home-work-process-2-title',
				'type'     => 'text',
				'title'    => __( 'Work Process Two Heading', 'hola' ),
				'desc'     => __( 'Please input the process title.', 'hola' ),
				'default'  => '02 DEVELOPMENT',
			),
			
			array(
				'id'       => 'home-work-process-2-icon',
				'type'     => 'select',
				'title'    => __('Select Process Icon', 'hola'),
				'desc'     => __('Please select process icon from the list.', 'hola').' <a href="http://rhythm.nikadevs.com/content/icons-et-line">Full list</a>.',
				// Must provide key => value pairs for select options
				'options'  => array(
					'icon-mobile' => '<span class="icon-mobile"></span> icon-mobile',
					'icon-laptop' => '<span class="icon-laptop"></span> icon-laptop',
					'icon-desktop' => '<span class="icon-desktop"></span> icon-desktop',
					'icon-tablet' => '<span class="icon-tablet"></span> icon-tablet',
					'icon-phone' => '<span class="icon-phone"></span> icon-phone',
					'icon-document' => '<span class="icon-document"></span> icon-document',
					'icon-documents' => '<span class="icon-documents"></span> icon-documents',
					'icon-search' => '<span class="icon-search"></span> icon-search',
					'icon-clipboard' => '<span class="icon-clipboard"></span> icon-clipboard',
					'icon-newspaper' => '<span class="icon-newspaper"></span> icon-newspaper',
					'icon-notebook' => '<span class="icon-notebook"></span> icon-notebook',
					'icon-book-open' => '<span class="icon-book-open"></span> icon-book-open',
					'icon-browser' => '<span class="icon-browser"></span> icon-browser',
					'icon-calendar' => '<span class="icon-calendar"></span> icon-calendar',
					'icon-presentation' => '<span class="icon-presentation"></span> icon-presentation',
					'icon-picture' => '<span class="icon-picture"></span> icon-picture',
					'icon-pictures' => '<span class="icon-pictures"></span> icon-pictures',
					'icon-video' => '<span class="icon-video"></span> icon-video',
					'icon-camera' => '<span class="icon-camera"></span> icon-camera',
					'icon-printer' => '<span class="icon-printer"></span> icon-printer',
					'icon-toolbox' => '<span class="icon-toolbox"></span> icon-toolbox',
					'icon-briefcase' => '<span class="icon-briefcase"></span> icon-briefcase',
					'icon-wallet' => '<span class="icon-wallet"></span> icon-wallet',
					'icon-gift' => '<span class="icon-gift"></span> icon-gift',
					'icon-bargraph' => '<span class="icon-bargraph"></span> icon-bargraph',
					'icon-grid' => '<span class="icon-grid"></span> icon-grid',
					'icon-expand' => '<span class="icon-expand"></span> icon-expand',
					'icon-focus' => '<span class="icon-focus"></span> icon-focus',
					'icon-edit' => '<span class="icon-edit"></span> icon-edit',
					'icon-adjustments' => '<span class="icon-adjustments"></span> icon-adjustments',
					'icon-ribbon' => '<span class="icon-ribbon"></span> icon-ribbon',
					'icon-hourglass' => '<span class="icon-hourglass"></span> icon-hourglass',
					'icon-lock' => '<span class="icon-lock"></span> icon-lock',
					'icon-megaphone' => '<span class="icon-megaphone"></span> icon-megaphone',
					'icon-shield' => '<span class="icon-shield"></span> icon-shield',
					'icon-trophy' => '<span class="icon-trophy"></span> icon-trophy',
					'icon-flag' => '<span class="icon-flag"></span> icon-flag',
					'icon-map' => '<span class="icon-map"></span> icon-map',
					'icon-puzzle' => '<span class="icon-puzzle"></span> icon-puzzle',
					'icon-basket' => '<span class="icon-basket"></span> icon-basket',
					'icon-envelope' => '<span class="icon-envelope"></span> icon-envelope',
					'icon-streetsign' => '<span class="icon-streetsign"></span> icon-streetsign',
					'icon-telescope' => '<span class="icon-telescope"></span> icon-telescope',
					'icon-gears' => '<span class="icon-gears"></span> icon-gears',
					'icon-key' => '<span class="icon-key"></span> icon-key',
					'icon-paperclip' => '<span class="icon-paperclip"></span> icon-paperclip',
					'icon-attachment' => '<span class="icon-attachment"></span> icon-attachment',
					'icon-pricetags' => '<span class="icon-pricetags"></span> icon-pricetags',
					'icon-lightbulb' => '<span class="icon-lightbulb"></span> icon-lightbulb',
					'icon-layers' => '<span class="icon-layers"></span> icon-layers',
					'icon-pencil' => '<span class="icon-pencil"></span> icon-pencil',
					'icon-tools' => '<span class="icon-tools"></span> icon-tools',
					'icon-tools-2' => '<span class="icon-tools-2"></span> icon-tools-2',
					'icon-scissors' => '<span class="icon-scissors"></span> icon-scissors',
					'icon-paintbrush' => '<span class="icon-paintbrush"></span> icon-paintbrush',
					'icon-magnifying-glass' => '<span class="icon-magnifying-glass"></span> icon-magnifying-glass',
					'icon-circle-compass' => '<span class="icon-circle-compass"></span> icon-circle-compass',
					'icon-linegraph' => '<span class="icon-linegraph"></span> icon-linegraph',
					'icon-mic' => '<span class="icon-mic"></span> icon-mic',
					'icon-strategy' => '<span class="icon-strategy"></span> icon-strategy',
					'icon-beaker' => '<span class="icon-beaker"></span> icon-beaker',
					'icon-caution' => '<span class="icon-caution"></span> icon-caution',
					'icon-recycle' => '<span class="icon-recycle"></span> icon-recycle',
					'icon-anchor' => '<span class="icon-anchor"></span> icon-anchor',
					'icon-profile-male' => '<span class="icon-profile-male"></span> icon-profile-male',
					'icon-profile-female' => '<span class="icon-profile-female"></span> icon-profile-female',
					'icon-bike' => '<span class="icon-bike"></span> icon-bike',
					'icon-hotairballoon' => '<span class="icon-hotairballoon"></span> icon-hotairballoon',
					'icon-globe' => '<span class="icon-globe"></span> icon-globe',
					'icon-genius' => '<span class="icon-genius"></span> icon-genius',
					'icon-map-pin' => '<span class="icon-map-pin"></span> icon-map-pin',
					'icon-dial' => '<span class="icon-dial"></span> icon-dial',
					'icon-chat' => '<span class="icon-chat"></span> icon-chat',
					'icon-heart' => '<span class="icon-heart"></span> icon-heart',
					'icon-cloud' => '<span class="icon-cloud"></span> icon-cloud',
					'icon-upload' => '<span class="icon-upload"></span> icon-upload',
					'icon-download' => '<span class="icon-download"></span> icon-download',
					'icon-target' => '<span class="icon-target"></span> icon-target',
					'icon-hazardous' => '<span class="icon-hazardous"></span> icon-hazardous',
					'icon-piechart' => '<span class="icon-piechart"></span> icon-piechart',
					'icon-speedometer' => '<span class="icon-speedometer"></span> icon-speedometer',
					'icon-global' => '<span class="icon-global"></span> icon-global',
					'icon-compass' => '<span class="icon-compass"></span> icon-compass',
					'icon-lifesaver' => '<span class="icon-lifesaver"></span> icon-lifesaver',
					'icon-clock' => '<span class="icon-clock"></span> icon-clock',
					'icon-aperture' => '<span class="icon-aperture"></span> icon-aperture',
					'icon-quote' => '<span class="icon-quote"></span> icon-quote',
					'icon-scope' => '<span class="icon-scope"></span> icon-scope',
					'icon-alarmclock' => '<span class="icon-alarmclock"></span> icon-alarmclock',
					'icon-refresh' => '<span class="icon-refresh"></span> icon-refresh',
					'icon-happy' => '<span class="icon-happy"></span> icon-happy',
					'icon-sad' => '<span class="icon-sad"></span> icon-sad',
					'icon-facebook' => '<span class="icon-facebook"></span> icon-facebook',
					'icon-twitter' => '<span class="icon-twitter"></span> icon-twitter',
					'icon-googleplus' => '<span class="icon-googleplus"></span> icon-googleplus',
					'icon-rss' => '<span class="icon-rss"></span> icon-rss',
					'icon-tumblr' => '<span class="icon-tumblr"></span> icon-tumblr',
					'icon-linkedin' => '<span class="icon-linkedin"></span> icon-linkedin',
					'icon-dribbble' => '<span class="icon-dribbble"></span> icon-dribbble',
				),
				'default'  => 'icon-bargraph',
			),
			array(
				'id'       => 'home-work-process-3-title',
				'type'     => 'text',
				'title'    => __( 'Work Process Three Heading', 'hola' ),
				'desc'     => __( 'Please input the process title.', 'hola' ),
				'default'  => '03 MARKETING',
			),
			
			array(
				'id'       => 'home-work-process-3-icon',
				'type'     => 'select',
				'title'    => __('Select Process Icon', 'hola'),
				'desc'     => __('Please select process icon from the list.', 'hola').' <a href="http://rhythm.nikadevs.com/content/icons-et-line">Full list</a>.',
				// Must provide key => value pairs for select options
				'options'  => array(
					'icon-mobile' => '<span class="icon-mobile"></span> icon-mobile',
					'icon-laptop' => '<span class="icon-laptop"></span> icon-laptop',
					'icon-desktop' => '<span class="icon-desktop"></span> icon-desktop',
					'icon-tablet' => '<span class="icon-tablet"></span> icon-tablet',
					'icon-phone' => '<span class="icon-phone"></span> icon-phone',
					'icon-document' => '<span class="icon-document"></span> icon-document',
					'icon-documents' => '<span class="icon-documents"></span> icon-documents',
					'icon-search' => '<span class="icon-search"></span> icon-search',
					'icon-clipboard' => '<span class="icon-clipboard"></span> icon-clipboard',
					'icon-newspaper' => '<span class="icon-newspaper"></span> icon-newspaper',
					'icon-notebook' => '<span class="icon-notebook"></span> icon-notebook',
					'icon-book-open' => '<span class="icon-book-open"></span> icon-book-open',
					'icon-browser' => '<span class="icon-browser"></span> icon-browser',
					'icon-calendar' => '<span class="icon-calendar"></span> icon-calendar',
					'icon-presentation' => '<span class="icon-presentation"></span> icon-presentation',
					'icon-picture' => '<span class="icon-picture"></span> icon-picture',
					'icon-pictures' => '<span class="icon-pictures"></span> icon-pictures',
					'icon-video' => '<span class="icon-video"></span> icon-video',
					'icon-camera' => '<span class="icon-camera"></span> icon-camera',
					'icon-printer' => '<span class="icon-printer"></span> icon-printer',
					'icon-toolbox' => '<span class="icon-toolbox"></span> icon-toolbox',
					'icon-briefcase' => '<span class="icon-briefcase"></span> icon-briefcase',
					'icon-wallet' => '<span class="icon-wallet"></span> icon-wallet',
					'icon-gift' => '<span class="icon-gift"></span> icon-gift',
					'icon-bargraph' => '<span class="icon-bargraph"></span> icon-bargraph',
					'icon-grid' => '<span class="icon-grid"></span> icon-grid',
					'icon-expand' => '<span class="icon-expand"></span> icon-expand',
					'icon-focus' => '<span class="icon-focus"></span> icon-focus',
					'icon-edit' => '<span class="icon-edit"></span> icon-edit',
					'icon-adjustments' => '<span class="icon-adjustments"></span> icon-adjustments',
					'icon-ribbon' => '<span class="icon-ribbon"></span> icon-ribbon',
					'icon-hourglass' => '<span class="icon-hourglass"></span> icon-hourglass',
					'icon-lock' => '<span class="icon-lock"></span> icon-lock',
					'icon-megaphone' => '<span class="icon-megaphone"></span> icon-megaphone',
					'icon-shield' => '<span class="icon-shield"></span> icon-shield',
					'icon-trophy' => '<span class="icon-trophy"></span> icon-trophy',
					'icon-flag' => '<span class="icon-flag"></span> icon-flag',
					'icon-map' => '<span class="icon-map"></span> icon-map',
					'icon-puzzle' => '<span class="icon-puzzle"></span> icon-puzzle',
					'icon-basket' => '<span class="icon-basket"></span> icon-basket',
					'icon-envelope' => '<span class="icon-envelope"></span> icon-envelope',
					'icon-streetsign' => '<span class="icon-streetsign"></span> icon-streetsign',
					'icon-telescope' => '<span class="icon-telescope"></span> icon-telescope',
					'icon-gears' => '<span class="icon-gears"></span> icon-gears',
					'icon-key' => '<span class="icon-key"></span> icon-key',
					'icon-paperclip' => '<span class="icon-paperclip"></span> icon-paperclip',
					'icon-attachment' => '<span class="icon-attachment"></span> icon-attachment',
					'icon-pricetags' => '<span class="icon-pricetags"></span> icon-pricetags',
					'icon-lightbulb' => '<span class="icon-lightbulb"></span> icon-lightbulb',
					'icon-layers' => '<span class="icon-layers"></span> icon-layers',
					'icon-pencil' => '<span class="icon-pencil"></span> icon-pencil',
					'icon-tools' => '<span class="icon-tools"></span> icon-tools',
					'icon-tools-2' => '<span class="icon-tools-2"></span> icon-tools-2',
					'icon-scissors' => '<span class="icon-scissors"></span> icon-scissors',
					'icon-paintbrush' => '<span class="icon-paintbrush"></span> icon-paintbrush',
					'icon-magnifying-glass' => '<span class="icon-magnifying-glass"></span> icon-magnifying-glass',
					'icon-circle-compass' => '<span class="icon-circle-compass"></span> icon-circle-compass',
					'icon-linegraph' => '<span class="icon-linegraph"></span> icon-linegraph',
					'icon-mic' => '<span class="icon-mic"></span> icon-mic',
					'icon-strategy' => '<span class="icon-strategy"></span> icon-strategy',
					'icon-beaker' => '<span class="icon-beaker"></span> icon-beaker',
					'icon-caution' => '<span class="icon-caution"></span> icon-caution',
					'icon-recycle' => '<span class="icon-recycle"></span> icon-recycle',
					'icon-anchor' => '<span class="icon-anchor"></span> icon-anchor',
					'icon-profile-male' => '<span class="icon-profile-male"></span> icon-profile-male',
					'icon-profile-female' => '<span class="icon-profile-female"></span> icon-profile-female',
					'icon-bike' => '<span class="icon-bike"></span> icon-bike',
					'icon-hotairballoon' => '<span class="icon-hotairballoon"></span> icon-hotairballoon',
					'icon-globe' => '<span class="icon-globe"></span> icon-globe',
					'icon-genius' => '<span class="icon-genius"></span> icon-genius',
					'icon-map-pin' => '<span class="icon-map-pin"></span> icon-map-pin',
					'icon-dial' => '<span class="icon-dial"></span> icon-dial',
					'icon-chat' => '<span class="icon-chat"></span> icon-chat',
					'icon-heart' => '<span class="icon-heart"></span> icon-heart',
					'icon-cloud' => '<span class="icon-cloud"></span> icon-cloud',
					'icon-upload' => '<span class="icon-upload"></span> icon-upload',
					'icon-download' => '<span class="icon-download"></span> icon-download',
					'icon-target' => '<span class="icon-target"></span> icon-target',
					'icon-hazardous' => '<span class="icon-hazardous"></span> icon-hazardous',
					'icon-piechart' => '<span class="icon-piechart"></span> icon-piechart',
					'icon-speedometer' => '<span class="icon-speedometer"></span> icon-speedometer',
					'icon-global' => '<span class="icon-global"></span> icon-global',
					'icon-compass' => '<span class="icon-compass"></span> icon-compass',
					'icon-lifesaver' => '<span class="icon-lifesaver"></span> icon-lifesaver',
					'icon-clock' => '<span class="icon-clock"></span> icon-clock',
					'icon-aperture' => '<span class="icon-aperture"></span> icon-aperture',
					'icon-quote' => '<span class="icon-quote"></span> icon-quote',
					'icon-scope' => '<span class="icon-scope"></span> icon-scope',
					'icon-alarmclock' => '<span class="icon-alarmclock"></span> icon-alarmclock',
					'icon-refresh' => '<span class="icon-refresh"></span> icon-refresh',
					'icon-happy' => '<span class="icon-happy"></span> icon-happy',
					'icon-sad' => '<span class="icon-sad"></span> icon-sad',
					'icon-facebook' => '<span class="icon-facebook"></span> icon-facebook',
					'icon-twitter' => '<span class="icon-twitter"></span> icon-twitter',
					'icon-googleplus' => '<span class="icon-googleplus"></span> icon-googleplus',
					'icon-rss' => '<span class="icon-rss"></span> icon-rss',
					'icon-tumblr' => '<span class="icon-tumblr"></span> icon-tumblr',
					'icon-linkedin' => '<span class="icon-linkedin"></span> icon-linkedin',
					'icon-dribbble' => '<span class="icon-dribbble"></span> icon-dribbble',
				),
				'default'  => 'icon-telescope',
			),
		
		)
	) );

	
	
	Redux::setSection( $opt_name, array(
		'title'      => __( 'News Section', 'hola' ),
		'desc'       => __( 'Settings for news section.', 'hola' ),
		'id'         => 'home-news',
		'subsection' => true,
		'fields'     => array(
			array(
				'id'       => 'home-news-heading',
				'type'     => 'text',
				'title'    => __( 'News Section Heading', 'hola' ),
				'desc'     => __( 'Please input the section title.', 'hola' ),
				'default'  => 'LATEST NEWS',
			),
			array(
				'id'       => 'home-news-description',
				'type'     => 'textarea',
				'title'    => __( 'News Section Description', 'hola' ),
				'desc'     => __( 'Please input the section description.', 'hola' ),
				'default'  => 'All their equipment and instruments are alive. I watched the beautiful yet terrific. Silver mist suffused the deck of the ship.',
			),
			
			array(
				'id'       => 'home-news-category',
				'type'     => 'select',
				'multi'    => true,
				'title'    => __('Select Categories', 'hola'),
				'subtitle' => __('Select one or many category for display', 'hola'),
				'desc'     => __('You can select all the categories if you like.', 'hola'),
				'placeholder'=> __('All','hola'),
				'sortable' => true,
				//Must provide key => value pairs for radio options
				'data' => 'terms',
				'args' => array(
					'taxonomies' => array( 'category' ),
				),
			),
		
		)
	) );

/*
 * <--- END SECTIONS
 */
